// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPFDataContext.YourOutputDirectory;

#nullable disable

namespace WPFDataContext.NET.Migrations
{
    [DbContext(typeof(MyFirstDatabaseContext))]
    [Migration("20240501125803_HotelReservationChangeToGuest")]
    partial class HotelReservationChangeToGuest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WPFDataContext.YourOutputDirectory.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.HasKey("AdminId")
                        .HasName("PK__Admin__719FE488C3368116");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("WPFDataContext.YourOutputDirectory.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Stilling")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EmployeeId")
                        .HasName("PK__Employee__7AD04F11F18084B2");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("WPFDataContext.YourOutputDirectory.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.HasKey("GuestId")
                        .HasName("PK__Guest__0C423C121AE80D67");

                    b.ToTable("Guest", (string)null);
                });

            modelBuilder.Entity("WPFDataContext.YourOutputDirectory.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelId"));

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotellKjede")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Navn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("HotelId")
                        .HasName("PK__Hotel__46023BDF13B164E0");

                    b.ToTable("Hotel", (string)null);
                });

            modelBuilder.Entity("WPFDataContext.YourOutputDirectory.HotelReservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("ReservationId")
                        .HasName("PK__HotelRes__B7EE5F245ED63343");

                    b.HasIndex("GuestId");

                    b.HasIndex("RoomId");

                    b.ToTable("HotelReservation", (string)null);
                });

            modelBuilder.Entity("WPFDataContext.YourOutputDirectory.HotelRoom", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int?>("NumberOfBeds")
                        .HasColumnType("int");

                    b.Property<bool?>("Occupied")
                        .HasColumnType("bit");

                    b.Property<string>("QualityOfRoom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SizeOfRoom")
                        .HasColumnType("int");

                    b.HasKey("RoomId")
                        .HasName("PK__HotelRoo__32863939F4289E21");

                    b.ToTable("HotelRoom", (string)null);
                });

            modelBuilder.Entity("WPFDataContext.YourOutputDirectory.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Etternavn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fornavn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PersonId")
                        .HasName("PK__Person__AA2FFBE597F6ADD6");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("WPFDataContext.YourOutputDirectory.Admin", b =>
                {
                    b.HasOne("WPFDataContext.YourOutputDirectory.Person", "AdminNavigation")
                        .WithOne("Admin")
                        .HasForeignKey("WPFDataContext.YourOutputDirectory.Admin", "AdminId")
                        .IsRequired()
                        .HasConstraintName("FK__Admin__AdminId__68487DD7");

                    b.Navigation("AdminNavigation");
                });

            modelBuilder.Entity("WPFDataContext.YourOutputDirectory.Employee", b =>
                {
                    b.HasOne("WPFDataContext.YourOutputDirectory.Person", "EmployeeNavigation")
                        .WithOne("Employee")
                        .HasForeignKey("WPFDataContext.YourOutputDirectory.Employee", "EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__Employee__Employ__656C112C");

                    b.Navigation("EmployeeNavigation");
                });

            modelBuilder.Entity("WPFDataContext.YourOutputDirectory.Guest", b =>
                {
                    b.HasOne("WPFDataContext.YourOutputDirectory.Person", "GuestNavigation")
                        .WithOne("Guest")
                        .HasForeignKey("WPFDataContext.YourOutputDirectory.Guest", "GuestId")
                        .IsRequired()
                        .HasConstraintName("FK__Guest__GuestId__628FA481");

                    b.Navigation("GuestNavigation");
                });

            modelBuilder.Entity("WPFDataContext.YourOutputDirectory.HotelReservation", b =>
                {
                    b.HasOne("WPFDataContext.YourOutputDirectory.Guest", "Guest")
                        .WithMany("HotelReservations")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__HotelRese__Guest__6EF57B66");

                    b.HasOne("WPFDataContext.YourOutputDirectory.HotelRoom", "Room")
                        .WithMany("HotelReservations")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK__HotelRese__RoomI__6FE99F9F");

                    b.Navigation("Guest");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("WPFDataContext.YourOutputDirectory.Guest", b =>
                {
                    b.Navigation("HotelReservations");
                });

            modelBuilder.Entity("WPFDataContext.YourOutputDirectory.HotelRoom", b =>
                {
                    b.Navigation("HotelReservations");
                });

            modelBuilder.Entity("WPFDataContext.YourOutputDirectory.Person", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Employee");

                    b.Navigation("Guest");
                });
#pragma warning restore 612, 618
        }
    }
}
